"use strict";
(() => {
  const fmt = n => Number(n).toFixed(2);
  const esc = s => String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  function probability(label, value, cls) { return `<div class="pe-prob"><span>${label}</span><b>${value}%</b><i><em class="${cls}" style="width:${value}%"></em></i></div>`; }
  function render(data) {
    const action = data.decision.toLowerCase();
    const plan = data.plan ? `<section class="pe-section"><h3>Trade plan</h3><div class="pe-plan"><span>ENTRY <b>${fmt(data.plan.entryLow)}–${fmt(data.plan.entryHigh)}</b></span><span>STOP <b>${fmt(data.plan.stop)}</b></span><span>TP1 <b>${fmt(data.plan.tp1)}</b></span><span>TP2 <b>${fmt(data.plan.tp2)}</b></span><span>R:R <b>1:${data.plan.rr}</b></span><span>INVALIDATION <b>${esc(data.plan.invalidation)}</b></span></div></section>` : `<div class="pe-wait">No executable trade. ${esc(data.waitReasons[0] || "Edge is below threshold.")}</div>`;
    return `<div class="pe-head"><div><div class="nc-pair">${data.symbol} · ${data.timeframe.toUpperCase()}</div><div class="nc-sub">${fmt(data.price)} · ${data.regime} · ${data.stale ? "STALE/CLOSED" : "LIVE COMPLETED CANDLES"}</div></div><button class="nc-refresh" data-refresh title="Refresh">↻</button></div>
      <div class="nc-call ${action}"><div class="nc-dirline"><span class="nc-arrow">${data.decision === "BUY" ? "↑" : data.decision === "SELL" ? "↓" : "—"}</span><span class="nc-dirtext">${data.decision}</span></div><div class="nc-caption">Trend ${data.trend} · ${data.alignment.count}/4 timeframes aligned</div><div class="nc-timerwrap"><span>Next candle closes</span><b class="nc-timer" data-close="${data.nextCloseAt}">--:--</b></div></div>
      <section class="pe-section"><h3>Probability</h3>${probability("BUY",data.probabilities.buy,"buy")}${probability("SELL",data.probabilities.sell,"sell")}${probability("NO TRADE",data.probabilities.noTrade,"wait")}</section>
      <section class="pe-section"><h3>Next 3 candles</h3><div class="nc-fclist">${data.forecasts.map(f=>`<div class="nc-fc ${f.direction.toLowerCase()}"><div class="nc-fc-top"><span class="nc-fc-label">Candle ${f.step}</span><span class="nc-fc-right"><b class="nc-fc-dir">${f.direction}</b><span class="nc-tag ${f.confidence>=65?"high":f.confidence>=55?"medium":"low"}">${f.confidence}%</span></span></div><div class="nc-fc-rows"><span>O<b>${fmt(f.open)}</b></span><span>H<b>${fmt(f.high)}</b></span><span>L<b>${fmt(f.low)}</b></span><span>C<b>${fmt(f.close)}</b></span></div></div>`).join("")}</div><p class="nc-note">Confidence decays for each forward candle; ranges are ATR projections, not guaranteed prices.</p></section>
      ${plan}<section class="pe-section"><h3>ICT / SMC evidence</h3><ul class="nc-why">${data.evidence.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></section>
      <section class="pe-section"><h3>Walk-forward validation</h3><div class="pe-metrics"><span>Directional accuracy<b>${data.validation.accuracy.toFixed(1)}%</b></span><span>Trade win rate<b>${data.validation.winRate.toFixed(1)}%</b></span><span>Samples<b>${data.validation.tested}</b></span><span>Expectancy<b>${data.validation.expectancy.toFixed(2)}R</b></span><span>Drawdown proxy<b>${data.validation.maxDrawdown.toFixed(1)}R</b></span><span>${data.regime} accuracy<b>${data.validation.currentRegimeAccuracy==null?"—":data.validation.currentRegimeAccuracy.toFixed(1)+"%"}</b></span></div></section>
      <div class="pe-risk">${esc(data.news.label)}. Paper-test first. Probabilities are estimates, not profit guarantees.</div>`;
  }
  function startClock(root) { clearInterval(root._clock); const tick=()=>{const el=root.querySelector("[data-close]");if(!el)return;const ms=Math.max(0,Number(el.dataset.close)-Date.now());el.textContent=`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}`};tick();root._clock=setInterval(tick,1000); }
  globalThis.JenvuUI = { render, startClock };
})();
