/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LlmRouteImport } from './routes/llm'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiEngineRouteImport } from './routes/ai-engine'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ApiSeedAdminRouteImport } from './routes/api/seed-admin'
import { Route as ApiPublicHooksGenerateInsightRouteImport } from './routes/api/public/hooks/generate-insight'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmRoute = LlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEngineRoute = AiEngineRouteImport.update({
  id: '/ai-engine',
  path: '/ai-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedAdminRoute = ApiSeedAdminRouteImport.update({
  id: '/api/seed-admin',
  path: '/api/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateInsightRoute =
  ApiPublicHooksGenerateInsightRouteImport.update({
    id: '/api/public/hooks/generate-insight',
    path: '/api/public/hooks/generate-insight',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engine': typeof AiEngineRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download': typeof DownloadRoute
  '/llm': typeof LlmRoute
  '/privacy': typeof PrivacyRoute
  '/signal': typeof SignalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/hooks/generate-insight': typeof ApiPublicHooksGenerateInsightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engine': typeof AiEngineRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download': typeof DownloadRoute
  '/llm': typeof LlmRoute
  '/privacy': typeof PrivacyRoute
  '/signal': typeof SignalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/api/public/hooks/generate-insight': typeof ApiPublicHooksGenerateInsightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-engine': typeof AiEngineRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/development': typeof DevelopmentRoute
  '/disclaimer': typeof DisclaimerRoute
  '/download': typeof DownloadRoute
  '/llm': typeof LlmRoute
  '/privacy': typeof PrivacyRoute
  '/signal': typeof SignalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/seed-admin': typeof ApiSeedAdminRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/hooks/generate-insight': typeof ApiPublicHooksGenerateInsightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-engine'
    | '/app'
    | '/auth'
    | '/contact'
    | '/development'
    | '/disclaimer'
    | '/download'
    | '/llm'
    | '/privacy'
    | '/signal'
    | '/sitemap.xml'
    | '/terms'
    | '/api/seed-admin'
    | '/insights/$slug'
    | '/insights/'
    | '/api/public/hooks/generate-insight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-engine'
    | '/app'
    | '/auth'
    | '/contact'
    | '/development'
    | '/disclaimer'
    | '/download'
    | '/llm'
    | '/privacy'
    | '/signal'
    | '/sitemap.xml'
    | '/terms'
    | '/api/seed-admin'
    | '/insights/$slug'
    | '/insights'
    | '/api/public/hooks/generate-insight'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-engine'
    | '/app'
    | '/auth'
    | '/contact'
    | '/development'
    | '/disclaimer'
    | '/download'
    | '/llm'
    | '/privacy'
    | '/signal'
    | '/sitemap.xml'
    | '/terms'
    | '/api/seed-admin'
    | '/insights/$slug'
    | '/insights/'
    | '/api/public/hooks/generate-insight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiEngineRoute: typeof AiEngineRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DevelopmentRoute: typeof DevelopmentRoute
  DisclaimerRoute: typeof DisclaimerRoute
  DownloadRoute: typeof DownloadRoute
  LlmRoute: typeof LlmRoute
  PrivacyRoute: typeof PrivacyRoute
  SignalRoute: typeof SignalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiSeedAdminRoute: typeof ApiSeedAdminRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiPublicHooksGenerateInsightRoute: typeof ApiPublicHooksGenerateInsightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm': {
      id: '/llm'
      path: '/llm'
      fullPath: '/llm'
      preLoaderRoute: typeof LlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-engine': {
      id: '/ai-engine'
      path: '/ai-engine'
      fullPath: '/ai-engine'
      preLoaderRoute: typeof AiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-admin': {
      id: '/api/seed-admin'
      path: '/api/seed-admin'
      fullPath: '/api/seed-admin'
      preLoaderRoute: typeof ApiSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-insight': {
      id: '/api/public/hooks/generate-insight'
      path: '/api/public/hooks/generate-insight'
      fullPath: '/api/public/hooks/generate-insight'
      preLoaderRoute: typeof ApiPublicHooksGenerateInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiEngineRoute: AiEngineRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DevelopmentRoute: DevelopmentRoute,
  DisclaimerRoute: DisclaimerRoute,
  DownloadRoute: DownloadRoute,
  LlmRoute: LlmRoute,
  PrivacyRoute: PrivacyRoute,
  SignalRoute: SignalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiSeedAdminRoute: ApiSeedAdminRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiPublicHooksGenerateInsightRoute: ApiPublicHooksGenerateInsightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
